$axure.loadCurrentPage({
  "url":"自动挂号功能_暂时不做_.html",
  "generationDate":new Date(1434526585785.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"921f3f6a3fff4cd2b07e2a46bb88b5ed",
    "type":"Axure:Page",
    "name":"自动挂号功能(暂时不做)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da24e77953964df19920dd36382a0e4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":70},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbdcf141d09e4872ab35fbb4affa582c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":70},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "da24e77953964df19920dd36382a0e4f":{
      "scriptId":"u0"},
    "dbdcf141d09e4872ab35fbb4affa582c":{
      "scriptId":"u1"}}});