$axure.loadCurrentPage({
  "url":"医院及相关数据.html",
  "generationDate":new Date(1434526603097.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"113cab33c16a4b85a27f735a6094ce6b",
    "type":"Axure:Page",
    "name":"医院及相关数据",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"96154c8ed783458586c438390f9a233d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":90},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"796b4eb816b344f289cc5f83e3cf58df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":90},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快医/u0.png"}},
{
          "id":"fdb1994c2296434a895540693bb3060c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":240},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b54bf48f9d8d4858822c9c75018fd133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":240},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快医/u0.png"}},
{
          "id":"bbb70aa6de694b44b45aad0ea7e50ddd",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1eaeb710ffa48dab8dfc411d8015d4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":150}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "96154c8ed783458586c438390f9a233d":{
      "scriptId":"u0"},
    "796b4eb816b344f289cc5f83e3cf58df":{
      "scriptId":"u1"},
    "fdb1994c2296434a895540693bb3060c":{
      "scriptId":"u2"},
    "b54bf48f9d8d4858822c9c75018fd133":{
      "scriptId":"u3"},
    "bbb70aa6de694b44b45aad0ea7e50ddd":{
      "scriptId":"u4"},
    "e1eaeb710ffa48dab8dfc411d8015d4d":{
      "scriptId":"u5"}}});